### ISSUE TITLE
ArcGIS Pro Toolbox unit selector

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#10]
Implement a unit selector in any tool

**Comment by ocsmit** [comment]
Implemented with f9d68f4

**Comment by HuidaeCho** [comment]
FYI, `query_mixed_geoms()` should only take rules (geoms) and projpicker_db. Unit should be part of geoms. This is because `query_mixed_geoms()` is the main entry point for everything.
