### ISSUE TITLE
More tool ideas for ArcGIS Pro Toolbox

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#13]
These tools will be useful:
* Guess *Raster* Projection (Current tool renamed to Guess Feature Class Projection)
* Reproject Raster
* Reproject Feature Class

**Comment by HuidaeCho** [comment]
* Match Coordinates

**Comment by ocsmit** [comment]
Match coordinates will be unable to be implemented within ArcGIS Pro due to pyproj dependencies.

**Comment by HuidaeCho** [comment]
> Match coordinates will be unable to be implemented within ArcGIS Pro due to pyproj dependencies.

You're right. Forget about it.

**Comment by ocsmit** [comment]
Didn't realize until I had already written the tool ;)

**Comment by HuidaeCho** [comment]
@ocsmit Please copy this file as `pyproj.py` in the same folder with `projpicker.pyt` and try match coordinates. It should work.
```python
import arcpy
import re

class Namespace: pass

class from_crs():
    def __init__(self, from_crs, to_crs, always_xy=False):
        from_crs = from_crs.split(":")[1]
        if re.match("^[0-9]+$", from_crs):
            self.from_crs = arcpy.SpatialReference(int(from_crs))
        else:
            self.from_crs = None
        to_crs = to_crs.split(":")[1]
        if re.match("^[0-9]+$", to_crs):
            self.to_crs = arcpy.SpatialReference(int(to_crs))
        else:
            self.to_crs = None
        self.always_xy = always_xy


    def transform(self, x, y):
        if None in (self.from_crs, self.to_crs):
            x = y = 1e+100
        else:
            if not self.always_xy:
                x, y = y, x
            point = arcpy.PointGeometry(arcpy.Point(x, y), from_crs)
            point = point.ProjectAs(to_crs)
            x, y = point.X, point.Y
        return x, y

Transformer = Namespace()
Transformer.from_crs = from_crs
```

**Comment by HuidaeCho** [comment]
@ocsmit Please try this implementation of pyproj.Transformer.from_crs (https://github.com/HuidaeCho/projpicker/commit/93158abe0bd481a53337d88515d02c1845897f42) from ArcGIS Pro. If it works, we can implement coordinate matching. It shouldn't be part of the core installation. When you install the toolbox, just copy this file to the projpicker directory where `projpicker.py` is (NOT `projpicker.pyt`).

**Comment by HuidaeCho** [comment]
Reopening this request and let me know after you try the mini `pyproj.py`.

**Comment by ocsmit** [comment]
Will be a bit as I finish up homework for the night. Will have it tested by end of the day.

**Comment by HuidaeCho** [comment]
Did it work?

**Comment by ocsmit** [comment]
Yes, need to think about best way to show result, but it works.
