### ISSUE TITLE
Tkinter GUI missing buttons

### ISSUE THREAD

**Issue by ocsmit** [HuidaeCho/projpicker#14]
![image](https://user-images.githubusercontent.com/55674113/121919864-72d4a080-cd05-11eb-944e-32a02606eb73.png)

Tested on my Windows 10 machine. Same issue regardless of how gui is called (shell, python, etc...).

**Comment by HuidaeCho** [comment]
Oh.. I guess it's a resizing issue? How did you make it smaller? It's a fixed size.

**Comment by ocsmit** [comment]
I am using v0.1.5.post6, so its not an outdated release issue. It does appear to be sizing but I have not touched sizing within the API at all. It is opening as that size.

**Comment by HuidaeCho** [comment]
Is that 800x400? I guess, it's a Windows' scaling thing.. Your font seems to be bigger compared to your native resolution?

**Comment by HuidaeCho** [comment]
But again, it works on the left frame... Weird..

**Comment by HuidaeCho** [comment]
Please try to run it directly from the source `projpicker.py`. Then, try to turn off any resolution scaling (https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10) if you have any.

**Comment by HuidaeCho** [comment]
Just tried rescaling, but everything worked fine..

**Comment by ocsmit** [comment]
I actually did have 125% scaling on, unbeknownst to me, but the issue persists even after setting the scaling to 100% and restarting. Ran it from source. Same issue. It works for me on my Linux machine so it has to be something with my windows.

**Comment by HuidaeCho** [comment]
Please try it on Zach's computer. It works there, I'm almost sure it's your Python. Maybe, reinstall Python?

**Comment by ocsmit** [comment]
I am not sure it can be purely my Python install because I am getting the same issue on my system python, my conda environment, and ArcGis Pro's python environment. Those are all separate python installations which should be sandboxed from the others.

**Comment by HuidaeCho** [comment]
Let me try it in my ArcGIS Pro.

**Comment by HuidaeCho** [comment]
OK.. it still works.. I just needed to add the sys.argv trick to the core.

**Comment by HuidaeCho** [comment]
It worked when you wrote the ArcGIS document before I add horizontal scroll bars.

**Comment by ocsmit** [comment]
Just rewound to 29587095e2d8879ae4834155587d23a8f17ee709 which was the last commit before the horizontal bars were added and it worked correctly.

![image](https://user-images.githubusercontent.com/55674113/121927329-e9c16780-cd0c-11eb-8906-b47fc145928f.png)

**Comment by HuidaeCho** [comment]
So it's the horizontal scrollbar?

**Comment by HuidaeCho** [comment]
ok, please go back to the latest commit and try removing list_hscrollbar and info_hscrollbar code blocks.

**Comment by HuidaeCho** [comment]
If you find anything and can make it work, please create a PR so I can review it. I need to understand why it doesn't work on your Windows machine. Also, please ask Zach to try it.

**Comment by HuidaeCho** [comment]
Looks to me like a default height of the Text widget... But why does it happen only on your machine.. We need a definite answer to this..

**Comment by HuidaeCho** [comment]
You also want to try removing `root.resizable(False, False)` and see if you can see the missing widgets by resizing the window and if the Text widget has a fixed height?

**Comment by ocsmit** [comment]
Zach's desktop has same issue
![image](https://user-images.githubusercontent.com/55674113/121934970-e8e10380-cd15-11eb-9262-146c588ec84e.png)

**Comment by ocsmit** [comment]
Also tested with virtual machine install of windows with same result

**Comment by HuidaeCho** [comment]
It's the default *minimum* height of the Text widget. Interesting. Line 214, add `height=1` after `width=20`.

**Comment by HuidaeCho** [comment]
Even the listbox has the same issue when resized to a very small size

**Comment by HuidaeCho** [comment]
![image](https://user-images.githubusercontent.com/7456117/121946687-2ef09400-cd23-11eb-86bd-71a26bc1dd41.png)

**Comment by HuidaeCho** [comment]
Experimentally, the minimum height for Listbox is 3 (even with height=1) and Text is 1.

For Listbox, setting it to 0 make it vertically infinitely long while setting it to 0 for Text has the same effect as setting it to 1. Inconsistent..

**Comment by ocsmit** [comment]
Interesting. Was just about to open a pull request for a temporary workaround while I finished the other open issues. However, height=1 works.

**Comment by HuidaeCho** [comment]
I was not able to find good documentation explaining all these. Bad..

**Comment by HuidaeCho** [comment]
Fixed in https://github.com/HuidaeCho/projpicker/commit/f019e935944138463866018788273e77e97074ca

**Comment by ocsmit** [comment]
Same,  even ``python3 -c "import tkinter as tk; help(tk.Text)"`` does not explain the options. I had believed that height and width were _not_ minimums but rather absolutes. Another workaround could be rewriting it to use [tkinters grid](https://www.pythontutorial.net/tkinter/tkinter-grid/) but that would obviously be more work and not entirely necessary.

**Comment by HuidaeCho** [comment]
When we expand and fill, absolute sizes don't make much sense in tkinter. The grid layout needs more planning, I feel, and is for more complicated UI.
