### ISSUE TITLE
Sphinx external link issue

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#15]
@ocsmit Please look into this issue https://github.com/sphinx-doc/sphinx/issues/9351. The link to GRASS GIS module in the sidebar doesn't work. Maybe, we should leave it like that for a while so the sphinx devs can check it? Anyway, we need to either fix this issue or just create an almost-empty page that simply forwards to the external link, which I don't prefer personally. I guess, it could be a theme issue?

**Comment by HuidaeCho** [comment]
No matter what, we should fix it ourselves cleanly and create a PR for Sphinx, ideally.

**Comment by ocsmit** [comment]
I agree. Will look into it. Would love for us to be able to fix it and contribute directly.

**Comment by ocsmit** [comment]
Appears to be a theme issue. Tested with default theme and it links to no problem.

**Comment by ocsmit** [comment]
Appears to be a theme issue. Tested with default theme and it links to no problem.

**Comment by ocsmit** [comment]
Check new docs. Should work.

**Comment by HuidaeCho** [comment]
Great! Looks great and more familiar. You also fixed the sentence case! Did you have to fork the Sphinx and make any changes? No support for sentence case from the upstream?
