### ISSUE TITLE
Boldface inconsistency in Sphinx outputs

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#2]
Some arguments' first line is boldfaced, but not all. Also, why does it boldface the first line? No boldface at all would look better.

![image](https://user-images.githubusercontent.com/7456117/120360160-72381500-c2d6-11eb-8914-86ca4397e6fe.png)

**Comment by HuidaeCho** [comment]
Looks like the first line from multi-line docstrings is boldfaced? Still, I don't agree with that decision. The first line from multi-line docstrings is no different from single-line docstrings at least in our case.

**Comment by ocsmit** [comment]
Looks like it is due to spacing within the text block of the 'help' parameter. E.g. 
```python
    output_exclusive.add_argument("-O", "--overwrite",
            action="store_true",
            help="""overwrite output files; applies to both projpicker.db and
                     query output file""")
```
produces 
![image](https://user-images.githubusercontent.com/55674113/120361852-5cc3ea80-c2d8-11eb-9516-7944fc4f16a4.png)

while 
```python
    output_exclusive.add_argument("-O", "--overwrite",
            action="store_true",
            help="overwrite output files; applies to both projpicker.db and "
                  "query output file")
```
produces the right formatting
![image](https://user-images.githubusercontent.com/55674113/120362056-a280b300-c2d8-11eb-9789-22dd37795281.png)

**Comment by HuidaeCho** [comment]
Hmm... But API has no "str"ings, but does the same. We cannot unindent docstrings to eliminate leading whitspaces.
![image](https://user-images.githubusercontent.com/7456117/120362862-8b8e9080-c2d9-11eb-9111-8846c4ca36f5.png)

**Comment by HuidaeCho** [comment]
> spacing within the text block

Is this behavior documented or just an unknown side effect?

**Comment by ocsmit** [comment]
Looks like new line even with the parameter fixes it.

```python
"""
 Returns:
        list: List of lists of parsed south, north, west, and east floats in
        decimal degrees.
"""
```
![image](https://user-images.githubusercontent.com/55674113/120364537-5f740f00-c2db-11eb-9934-671511425a18.png)

**Comment by ocsmit** [comment]
Did not mean to close the issue. Didn't realize referencing the issue with my commit would close it. Anyways, see the current [docs](https://projpicker.readthedocs.io/en/latest/index.html) for fixed text.

**Comment by HuidaeCho** [comment]
Reading https://google.github.io/styleguide/pyguide.html...

**Comment by HuidaeCho** [comment]
Let's keep it open until we find any *documented* reason for this behavior. Indentation in the Returns section seems to inconsistent with the other sections in the Google style..

**Comment by HuidaeCho** [comment]
> Returns section seems to inconsistent with the other sections in the Google style..

I think this is because the Returns section has no argument name and only has one *thing* to describe as opposed to arguments?

**Comment by HuidaeCho** [comment]
Oh! It's not actually boldface, it's dt and dd.

**Comment by ocsmit** [comment]
See https://github.com/sphinx-doc/sphinx/issues/6472

It appears it was a change that was implemented with html5. Using the ''html4_writer = True'' in the configuration makes docs which look like 
![image](https://user-images.githubusercontent.com/55674113/120368769-79fcb700-c2e0-11eb-911d-9f587e2133ec.png)
and do not add <dt> and <dd> when multi-line doc strings are formatted as they are supposed to be.

**Comment by HuidaeCho** [comment]
OK. A couple points:
* `Returns` section should have only one indentation level to avoid dt+dd.
* `Args` and `Raises` have *items* and each item can have 2nd-level indentations
* `help=` shouldn't be a multi-line string. When splitting it into multiple lines, let's indent them once, not to the equal symbol to save horizontal space:

Yes:
```python
parser.add_argument(
    description="long description"
        "second line is somewhat long")
```
No:
```python
parser.add_argument(
    description="long description"
                "second line"
                "is somewhat long")
```
