### ISSUE TITLE
GUI bbox drawing

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#25]
When a CRS is selected from the desktop GUI, a red rectangle is overlaid and zoomed to to show the bbox of the CRS.

**Comment by HuidaeCho** [comment]
Research how to draw a rectangle programmatically.

**Comment by ocsmit** [comment]
![image](https://user-images.githubusercontent.com/55674113/124519750-3225ef80-ddb8-11eb-90e6-9ee3d2903875.png)

**Comment by HuidaeCho** [comment]
Looks great! Check my commit #27.

**Comment by HuidaeCho** [comment]
BTW, your system font seems to be fixed-width? My CRS Info is not aligned.

![image](https://user-images.githubusercontent.com/7456117/124525356-07926180-ddcd-11eb-855b-539d9328a41e.png)

Please see if it's an easy fix.
