### ISSUE TITLE
Missing argparse argument in PyPI package

### ISSUE THREAD

**Issue by ocsmit** [HuidaeCho/projpicker#26]
`-m, --max` arguments missing from current PyPi version.

![image](https://user-images.githubusercontent.com/55674113/124500502-e3fbf680-dd8d-11eb-8956-b2c954297550.png)

should be 
![image](https://user-images.githubusercontent.com/55674113/124500446-cdee3600-dd8d-11eb-85b0-a47ab0c35bcc.png)

Version: 0.1.6

**Comment by HuidaeCho** [comment]
That's because it was added after 0.1.6. I'll release 0.1.6.post1 soon if I don't have anything to add.

**Comment by HuidaeCho** [comment]
0.1.6.post1 is just released. Please try it again.

**Comment by ocsmit** [comment]
Great. Was unsure in which version it was added. Works now.
