### ISSUE TITLE
Option to display PROJ wkt if proj install is found?

### ISSUE THREAD

**Issue by ocsmit** [HuidaeCho/projpicker#30]
Similar to how GRASS and QGIS show the PROJ wkt, we could have an option to switch between the ProjPicker Query info and  the PROJ wkt if a PROJ isntallation is found.

![image](https://user-images.githubusercontent.com/55674113/124652708-6c4fc980-de6a-11eb-8926-0d0e5f44ead2.png)

![image](https://user-images.githubusercontent.com/55674113/124653200-01eb5900-de6b-11eb-94c3-a65a457996e8.png)
Potential button placement are shown at [1] and [2] 

We could implement a bootstrap version of pyprojs code to detect if PROJ is installed found [here](https://github.com/pyproj4/pyproj/blob/master/pyproj/datadir.py).

**Comment by HuidaeCho** [comment]
Like this idea. What about using tabs above the CRS Info box, if possible?

**Comment by ocsmit** [comment]
Tabs are [possible](https://pythonspot.com/wxpython-tabs/), but  I think a single radio button to switch the output to the PROJ WKT would look good with the other logical operator options.

**Comment by HuidaeCho** [comment]
Moved to https://github.com/HuidaeCho/projpicker-gui/issues/2
