### ISSUE TITLE
Javascript error still present at startup

### ISSUE THREAD

**Issue by ocsmit** [HuidaeCho/projpicker#35]
JavaScript error at startup caused by `pushGeometryChunk` is still present.

![image](https://user-images.githubusercontent.com/55674113/124819713-996bad00-df3a-11eb-8850-c40e390f7973.png)

**Comment by HuidaeCho** [comment]
Let me look into it after class.

**Comment by HuidaeCho** [comment]
When does it happen? I cannot reproduce it.

**Comment by ocsmit** [comment]
For me it is immediately when the application is started.

**Comment by HuidaeCho** [comment]
You're actually getting the popup window?

**Comment by HuidaeCho** [comment]
OK.. I guess I know what's happening on your machine. wxPython started parsing the HTML and set the initial title when it hits `<title>` tag before even reading the definition of `pushGeometryChunk()`. That triggers the title changed event, but pushGeometryChunk() is not defined yet.

**Comment by HuidaeCho** [comment]
Please try  ebe9f5d.

**Comment by ocsmit** [comment]
Works.
