### ISSUE TITLE
TODO: Repo cleanup

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#41]
@ocsmit I'm going to create a new archive branch for [my JS files](https://github.com/HuidaeCho/projpicker-js) in the core repo. Do you have anything to keep in [the gui repo](https://github.com/HuidaeCho/projpicker-gui)? Is the wxpython branch there the same as the archived_gui branch in the core repo? What about electron and main? This project was really fun and I learned a lot. I don't want to lose any significant code.

**Comment by HuidaeCho** [comment]
Maybe, we should keep everything as is. I deleted projpicker-web only (already integrated into the core).

**Comment by ocsmit** [comment]
I think keeping everything as it is would work, especially so we can keep the commit history intact!
