### ISSUE TITLE
Web: Editing Polygons

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#42]
I cannot edit polygons. It says `Error: shape edges cannot cross!`, but they don't. Editing points and rectangles works fine.

**Comment by ocsmit** [comment]
That is odd. I have no issues editing polygons. Do you have an example?

**Comment by HuidaeCho** [comment]
Hmm... it's not always reproducible. On the same machine, it sometimes works and other times not. If anything, I think this is a Leaflet bug.
