### ISSUE TITLE
Doc: Document any features missing in the documentation

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#43]
* <del>Core GUI</del>
* <del>Server: different modes</del>
* <del>ProjPicker Web</del>
* Environment variables
  * `PROJPICKER_VERBOSE`
  * `PROJPICKER_GUI`
  * `PROJPICKER_LATITUDE`
  * `PROJPICKER_LONGITUDE`
  * `PROJPICKER_ZOOM`
  * `PROJPICKER_DZOOM`

**Comment by ocsmit** [comment]
Working on documenting GUI now.
