### ISSUE TITLE
GUI: Try ttk widgets only

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#44]
Hopefully better and native look & feel

**Comment by HuidaeCho** [comment]
tk widgets except for the CRS list and tabs (only available in ttk)
![image](https://user-images.githubusercontent.com/7456117/127355695-4ca2a7fb-0cc3-4388-acfa-c1620c405a4a.png)

ttk widgets if available (Frame, Scrollbar, Button, Label)
![image](https://user-images.githubusercontent.com/7456117/127356092-2bc42eef-f0ad-48d8-88d3-691122545b77.png)

The main (only visual?) difference is buttons (flat, native look on Windows) and scrollbar grabbers (taller, better?). I have to use ttk.Treeview and ttk.Notebook, so there is no point in trying to avoid ttk widgets. Maybe, mixing tk and ttk widgets can be even worse?

**Comment by HuidaeCho** [comment]
On Linux. tk + ttk widgets
![image](https://user-images.githubusercontent.com/7456117/127356895-78eb600f-ee49-4a3c-bf2f-72d0fc6ce8f5.png)

ttk widgets if available
![image](https://user-images.githubusercontent.com/7456117/127357006-897ef529-1fcc-4936-b69a-7680ac05ee52.png)

ttk buttons are wider, but otherwise they look the same. Scrollbar arrows look different and are more consistent with combobox arrows. Combobox, Notebook, Progressbar, Separator, Sizergrip, and Treeview are only available in tkinter.ttk.

**Comment by HuidaeCho** [comment]
To summarize my test,
1. ttk buttons are wider and (GOOD)
2. look native at least on Windows. (GOOD)
3. ttk scrollbar grabbers are taller and (GOOD)
4. their arrows look more consistent with combobox (ttk only) arrows on Linux. (GOOD)

Other than these four points, I cannot see any other visual differences. Also, I cannot avoid using ttk altogether unless I want to reimplement the Combobox and Notebook widgets myself. So... let's migrate tk widgets to ttk's when possible.

**Comment by HuidaeCho** [comment]
Replaced tk widgets with ttk widgets in 813073a.

**Comment by HuidaeCho** [comment]
Just one thing.. Where the horizontal and vertical scrollbars meet, the arrow boxes are not squares anymore and they are not well aligned. Am I being too picky?

**Comment by HuidaeCho** [comment]
https://stackoverflow.com/a/66338658/16079666

**Comment by ocsmit** [comment]
Tried the [azure](https://github.com/rdbende/Azure-ttk-theme) theme by adding it as a submodule to my local repo. I think it looks good. 

![image](https://user-images.githubusercontent.com/55674113/127400137-f608c25a-6e39-47cc-9ab2-d2475ff84752.png)

**Comment by ocsmit** [comment]
Might be something to consider.
