### ISSUE TITLE
Option to save query from query builder and load in query to GUI. 

### ISSUE THREAD

**Issue by ocsmit** [HuidaeCho/projpicker#45]
I think it would be very useful to be able to save the query that you create for later use, sharing, and editing.

**Comment by HuidaeCho** [comment]
I think for this, we need to add a menu at the top instead of exposing these features as [Save] and [Open] buttons.

**Comment by ocsmit** [comment]
How about a pop up menu when you write click the Query frame? I have it complete and am about to push it on a new branch.

**Comment by ocsmit** [comment]
see f8ca1610976a62fba5593c7c6f97b73f30823e1c

**Comment by ocsmit** [comment]
I think this way is clean and non intrusive. Let me know.

**Comment by HuidaeCho** [comment]
Context menu.. That's a good idea.

**Comment by HuidaeCho** [comment]
polishing it now.
