### ISSUE TITLE
Sentence case in the documentation

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#7]
Is it possible to convert this Title Case to Sentence case to be consistent?

https://projpicker.readthedocs.io/en/latest/command_line_options.html#Positional%20Arguments

"Positional Arguments" => "Positional arguments"? I guess, this is sphinx, not even argparse because argparse says "optional arguments", not "Named Arguments".

**Comment by HuidaeCho** [comment]
If it's not possible at all, hmm... I'll have to change everything else to Title Case, which I personally don't like because it can look busy when titles become long.

**Comment by ocsmit** [comment]
This is a [sphinx-argparse](https://github.com/alex-rudakov/sphinx-argparse) issue. The maintained iteration for sphinx argparse ([sphinx-argparse-cli](https://github.com/gaborbernat/sphinx-argparse-cli)) generates all lowercase headers and in my opinion does not look as good and is more busy within the actual body and description of the options. See below
![image](https://user-images.githubusercontent.com/55674113/122277524-fcc26c00-ceb3-11eb-8dcf-f29aabf10cbf.png)

**Comment by ocsmit** [comment]
Created a fork of [sphinx-argparse](https://github.com/alex-rudakov/sphinx-argparse) and changed it to use sentence case for headers

- https://github.com/ocsmit/sphinx-argparse

I am going to try to see if read the docs can install directly from this source

**Comment by ocsmit** [comment]
Weird. RTD will install directly from my fork on GitHub, but still uses all upper case. When I build it locally however with my fork installed with pip, it is sentence case

![image](https://user-images.githubusercontent.com/55674113/122281990-e5d24880-ceb8-11eb-8cc8-f922a4b2c159.png)

**Comment by ocsmit** [comment]
I believe this is a read the docs issue. Currently it is building any changes I make, but none of the changes are actually being applied to the docs. This includes the theme as well.

**Comment by HuidaeCho** [comment]
Was hardcoded! Bad... https://github.com/ocsmit/sphinx-argparse/commit/c213773d8807a6cac0003561fb123d0bcbc08a88

**Comment by HuidaeCho** [comment]
Should I do anything on my side to use your fork?

**Comment by HuidaeCho** [comment]
Can we remove that Ad?

**Comment by ocsmit** [comment]
> Was hardcoded! Bad... [ocsmit/sphinx-argparse@c213773](https://github.com/ocsmit/sphinx-argparse/commit/c213773d8807a6cac0003561fb123d0bcbc08a88)

I was surprised it was hardcoded. I am going to try to make the header case an option and open a pull request. 

Nothing to do on your side, Read the docs just pulls and installs directly from my fork. 

As for the ad, read https://docs.readthedocs.io/en/stable/advertising/index.html. I actually hadn't realized it but I have no idea how the 'press theme' did not have any ad at all.

**Comment by HuidaeCho** [comment]
Maybe, the broken external link paid for the Ads for us. lol...

**Comment by HuidaeCho** [comment]
So if it's a theme issue, we can technically fix the press theme and go back to no Ads..

**Comment by ocsmit** [comment]
I don't see why not.

**Comment by HuidaeCho** [comment]
Fixed it locally and works fine, but adding `git+https://github.com/HuidaeChoi/sphinx_press_theme.git@master` to requirements.txt doesn't work on RTD...

**Comment by HuidaeCho** [comment]
https://projpicker.readthedocs.io/en/latest/?badge=latest

**Comment by HuidaeCho** [comment]
Any idea how to fix it?

**Comment by ocsmit** [comment]
It does not work locally for me either

**Comment by HuidaeCho** [comment]
Overwrote your press theme with mine?

**Comment by HuidaeCho** [comment]
https://github.com/HuidaeCho/sphinx_press_theme

**Comment by ocsmit** [comment]
Correct, uninstalled press theme and tried it with "pip install -r requirements.txt" and cloning your fork and installing with "pip install -e ."

**Comment by HuidaeCho** [comment]
Worked or not? Please checkout fix_sidebar_external_links branch.

Created a PR to avoid all this headache: https://github.com/schettino72/sphinx_press_theme/pull/59

**Comment by ocsmit** [comment]
Neither method worked locally for me

**Comment by ocsmit** [comment]
Looks like it is a local thing for me, the assets aren't building when I install locally

**Comment by HuidaeCho** [comment]
I think this is a CSS issue.

**Comment by HuidaeCho** [comment]
The resource from “https://projpicker.readthedocs.io/en/latest/_static/theme.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).index.html

From the upstream..

**Comment by HuidaeCho** [comment]
hmm... that file doesn't exist.

**Comment by HuidaeCho** [comment]
trying `yarn build`

**Comment by HuidaeCho** [comment]
Yeah.. Back to no Ads. Please check https://projpicker.readthedocs.io/en/latest/index.html from your side. I think RTD still doesn't know how to insert Ads to the Press Theme..

**Comment by ocsmit** [comment]
Everything works. Super weird about the ads though...
